export { default as Button } from './Button/Button';
export { default as Header } from './Header/Header';
export { default as Input } from './Input/Input';
export { default as Select } from './Select/Select';
export { default as UploadImage } from './UploadImage/UploadImage';
export { default as RadioButtons } from './RadioButtons/RadioButtons';
export { default as Success } from './Success/Success';
export { default as Record } from './Record/Record';
export { default as InfoText } from './InfoText/InfoText';
